[Variables]
 ;==============================================================================
 ; CONFIGURATION
 ;==============================================================================
 ThemeColor       =50,150,220
 ThemeFont        =Planer
 DefaultFont      =Segoe
 Topic            ="TECHNOLOGY"
 Locale           =?hl=en-US&gl=US&ceid=US:en
 SelectedLocale   =1
 Selected         =3
 Item             =.*<item>.*<title>(.*)</title>.*<link>(.*)</link>
 ItemOver         ="[\x25B6]"
 ItemLeave        ="[\x25B7]"
 ItemFontSize     =12
 ItemWidth        =500
 ItemHeight       =30
 TopicText        =13
 TitleText        =40
 
 ;==============================================================================
 ; LANGUAGES
 ;==============================================================================
 EN=?hl=en-US&gl=US&ceid=US:en
 GR=?hl=el&gl=GR&ceid=GR%3Ael
 RU=?hl=ru&gl=RU&ceid=RU%3Aru

 ;==============================================================================
 ; COLOR PALETTE
 ;==============================================================================
 White            = 255,255,255
 Grey             = 200,200,200
 DarkGrey         = 100,100,100
